version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: test-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - /home/docker/gymdata/:/var/lib/mysql/
    
  backend:
    build: ./
    ports:
      - 8000:8000